version: "3.3"
services:
#  web:
#    build: .
#    ports:
#      - "8000:8000"
  db:    
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data:delegated
  db-test:    
    image: postgres:12.2-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=testpostgres
      - POSTGRES_PASSWORD=postgres
  spid-idp-test:
    image: italia/spid-testenv2
    ports:
      - 8088:8088
    volumes:
      - type: bind
        source: ./spid/testconf
        target: /app/conf
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
volumes:
  db-data: